
CREATE TABLE USUARIO (
IdUsuario INT NOT NULL PRIMARY KEY IDENTITY(1,1),
LoginUsuario VARCHAR(20) NOT NULL UNIQUE,
NomeUsuario VARCHAR(100) NOT NULL,
EmailUsuario VARCHAR(100) NOT NULL UNIQUE,
SenhaUsuario VARCHAR(50) NOT NULL)

CREATE TABLE CLIENTE(
IdCliente INT NOT NULL PRIMARY KEY IDENTITY(1,1),
CodigoCliente VARCHAR(20) NOT NULL UNIQUE,
NomeCliente VARCHAR(100) NOT NULL,
CPF_CNPJ VARCHAR(20) NOT NULL UNIQUE,
EmailCliente VARCHAR(100) NOT NULL UNIQUE,
TelefoneCliente VARCHAR(20) NOT NULL)

CREATE TABLE CATEGORIA(
IdCategoria INT NOT NULL PRIMARY KEY IDENTITY(1,1),
CodigoCategoria VARCHAR(20) NOT NULL UNIQUE,
NomeCategoria VARCHAR(100) NOT NULL)

CREATE TABLE PRODUTO(
IdProduto INT NOT NULL PRIMARY KEY IDENTITY(1,1),
CodigoProduto VARCHAR(20) NOT NULL UNIQUE,
DescricaoProduto VARCHAR(100) NOT NULL,
QuantidadeProduto NUMERIC(20,6) NOT NULL,
PrecoProduto NUMERIC(20,6) NOT NULL,
IdCategoria INT CONSTRAINT FK_IdCategoria_PRODUTO_CATEGORIA FOREIGN KEY (IdCategoria) REFERENCES CATEGORIA(IdCategoria))

CREATE TABLE DOCUMENTO(
IdDocumento INT NOT NULL PRIMARY KEY IDENTITY(1,1),
NumeroDocumento INT NOT NULL UNIQUE,
DataDocumento DATETIME NOT NULL,
ValorTotalDocumento NUMERIC (20,6) NOT NULL,
IdCliente INT CONSTRAINT FK_IdCliente_DOCUMENTO_CLIENTE FOREIGN KEY (IdCliente) REFERENCES CLIENTE(IdCliente))

CREATE TABLE DOCUMENTO_ITEM(
IdDocumento INT NOT NULL CONSTRAINT FK_IdDocumento_DOCUMENTO_ITEM_DOCUMENTO FOREIGN KEY (IdDocumento) REFERENCES DOCUMENTO(IdDocumento),
IdProduto INT NOT NULL CONSTRAINT FK_IdProduto_DOCUMENTO_ITEM_PRODUTO FOREIGN KEY (IdProduto) REFERENCES PRODUTO(IdProduto),
QuantidadeProduto NUMERIC (20,6) NOT NULL,
ValorUnitarioItem NUMERIC (20,6) NOT NULL,
ValorTotalItem NUMERIC (20,6) NOT NULL,
PRIMARY KEY (IdDocumento,IdProduto))